apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: mongo-hpa
spec:
 maxReplicas: 5
 minReplicas: 1
 scaleTargetRef:
   apiVersion: extensions/v1beta1
   kind: Deployment
   name: mongo
 targetCPUUtilizationPercentage: 50