version: '3'
services:
  eureka-server:
    image: eureak-server:1.0
    container_name: eureka-server
    expose:
    - "8761"
    ports: 
    - 8761:8761

  mongo:
    image: mongo:latest
    container_name: mongo
    expose:
    - "27018"
    ports: 
    - 27017:27017

  app-admin-microservice:
    image: app-admin-microservice:1.0
    expose:
    - "8281"
    ports:
    - 8271:8281
    environment:
      - JAVA_OPTS=
            -DEUREKA_SERVER=http://eureka-server:8761/eureka -DHOST_NAME=mongo
      
    links: 
        - eureka-server
        - mongo
        
  app-employee-microservice:
    image: app-employee-microservice:1.0
    expose:
    - "8181"
    ports:
    - 8171:8181
    environment:
      - JAVA_OPTS=
            -DEUREKA_SERVER=http://eureka-server:8761/eureka -DHOST_NAME=mongo
      
    links: 
        - eureka-server
        - mongo
        
  app-management-service:
    image: app-management-service:1.0
    expose:
    - "8580"
    ports:
    - 8371:8580
    environment:
      - JAVA_OPTS=
            -DEUREKA_SERVER=http://eureka-server:8761/eureka
      
    links: 
        - eureka-server
        