apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
   
spec:
  replicas: 1
  template:
    metadata:
      name: eureka-pod
      labels:
        app: eureka-app
    spec:
      containers:
        - name: eureka-container
          image: ashu847/eureka-server:1.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '100m'
              memory: '1G'
            requests:
              cpu: '2m'
              memory: '400Mi'
  selector:
    matchLabels:
     app: eureka-app