apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    app: eureka-app
spec:
  selector:
    app: eureka-app
  type: LoadBalancer
  ports:
  - nodePort: 30020
    port: 80
    targetPort: 8761
