apiVersion: v1
kind: Service
metadata:
  name: management-service
  labels:
    app: management-app
spec:
  selector:
    app: management-app
  type: LoadBalancer
  ports:
  - nodePort: 30030
    port: 80
    targetPort: 8580
