server:
 port: 8381

spring:
 application:
    name: app-management-service

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:9190/eureka
debug: true 

   
management:
  endpoints:
    web:
      exposure:
        include: '*'  
  