server:
  port: 9190
  
spring:
  application:
    name: employee-eureka-server
    
eureka:
  instance:
    hostname: "${eureka-0}.eureka"
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS}