apiVersion: v1
kind: Service
metadata:
  name: admin-service
  labels:
    app: admin-app
spec:
  selector:
    app: admin-app
  type: LoadBalancer
  ports:
  - nodePort: 30001
    port: 80
    targetPort: 8281
