apiVersion: v1
kind: Service
metadata:
  name: employee-service
  labels:
    app: employee-app
spec:
  selector:
    app: employee-app
  type: LoadBalancer
  ports:
  - nodePort: 30010
    port: 80
    targetPort: 8181
